services:
  caddy:
    profiles: [prod] # exclude from default local run

  api:
    ports:
      - "8080:8080"

  web:
    ports:
      - "3000:3000"
    environment:
      - NUXT_API_BASE=http://api:8080/api
