package main

import (
	"strings"
	"testing"
)

// TestGenerateGolden verifies that key interfaces render with the expected
// field names, types, and optionality. It is intentionally narrow — it checks
// representative cases rather than the full file so the test stays useful as
// the contract evolves.
func TestGenerateGolden(t *testing.T) {
	buf, err := generate(contract)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	out := string(buf)

	// Header must be present.
	if !strings.Contains(out, "// Code generated by api/cmd/gentypes. DO NOT EDIT.") {
		t.Error("missing DO NOT EDIT header")
	}

	// Dependency — simple required fields.
	assertContains(t, out, "export interface Dependency {")
	assertContains(t, out, "  name: string;")
	assertContains(t, out, "  constraint: string;")

	// DependencyTree — slice and map fields.
	assertContains(t, out, "export interface DependencyTree {")
	assertContains(t, out, "  required: Dependency[];")
	assertContains(t, out, "  extras: Record<string, Dependency[]>;")

	// DataPoint — omitempty field must be optional.
	assertContains(t, out, "export interface DataPoint {")
	assertContains(t, out, "  date?: string;")
	assertContains(t, out, "  downloads: number;")

	// RepoInfo — archived must be required boolean (Go has no omitempty).
	assertContains(t, out, "export interface RepoInfo {")
	assertContains(t, out, "  archived: boolean;")
	assertNotContains(t, out, "  archived?: boolean;")

	// TypeSupport — status must use union literal override.
	assertContains(t, out, `  status: "typed" | "stubs" | "untyped";`)

	// DocSymbol — kind must use union literal override.
	assertContains(t, out, `  kind: "function" | "class" | "exception";`)

	// DocsResponse — available is required bool (no omitempty on Go side).
	assertContains(t, out, "export interface DocsResponse {")
	assertContains(t, out, "  available: boolean;")

	// Pointer fields → T | null (DocSymbol.returns is *DocReturn).
	assertContains(t, out, "  returns?: DocReturn | null;")

	// CombinedStats.date_range is *DateRange — should be optional + nullable.
	assertContains(t, out, "  date_range?: DateRange | null;")
}

func assertContains(t *testing.T, s, substr string) {
	t.Helper()
	if !strings.Contains(s, substr) {
		t.Errorf("generated output missing expected string:\n  want: %q", substr)
	}
}

func assertNotContains(t *testing.T, s, substr string) {
	t.Helper()
	if strings.Contains(s, substr) {
		t.Errorf("generated output contains unexpected string:\n  got: %q", substr)
	}
}
