// gentypes generates TypeScript interface definitions from Go response structs,
// and (optionally) the OpenAPI 3.1 description of the HTTP surface.
// Usage: go run ./cmd/gentypes -out ../web/app/types/api.gen.ts \
//	-openapi internal/handler/openapi.gen.json
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"reflect"
	"strings"

	"github.com/pypx/api/internal/changelog"
	"github.com/pypx/api/internal/conda"
	"github.com/pypx/api/internal/enrichment"
	gh "github.com/pypx/api/internal/github"
	"github.com/pypx/api/internal/handler"
	"github.com/pypx/api/internal/osv"
	"github.com/pypx/api/internal/pypi"
	"github.com/pypx/api/internal/search"
	"github.com/pypx/api/internal/stats"
	"github.com/pypx/api/internal/textfmt"
)

// contract is the ordered list of types to emit. Order matches api.ts.
// Each entry is a zero-value of the struct to emit.
var contract = []any{
	handler.APIRootResponse{},
	handler.PackageResponse{},
	handler.FileInfo{},
	enrichment.PythonVersionInfo{},
	enrichment.Dependency{},
	enrichment.DependencyTree{},
	enrichment.PlatformCoverage{},
	enrichment.QuarterCount{},
	enrichment.ReleaseCadence{},
	enrichment.Maintainer{},
	handler.VersionInfo{},
	handler.DateRange{},
	handler.CombinedStats{},
	stats.DataPoint{},
	search.PackageEntry{},
	gh.RepoOwner{},
	gh.RepoInfo{},
	changelog.Entry{},
	handler.ChangelogResponse{},
	osv.VulnInfo{},
	handler.SecurityResponse{},
	pypi.TypeSupport{},
	conda.CondaForgeInfo{},
	handler.ExtrasResponse{},
	handler.DocParam{},
	handler.DocReturn{},
	handler.DocRaise{},
	handler.DocSymbol{},
	handler.DocModule{},
	handler.DocsResponse{},
	// Compare/diff JSON routes marshal the textfmt input structs directly
	// (handler.CompareHandler.GetJSON, handler.DiffHandler.GetJSON).
	textfmt.CompareInput{},
	textfmt.SkippedPackage{},
	textfmt.ComparePackageInput{},
	textfmt.DiffInput{},
	textfmt.DepDiff{},
	textfmt.DepBump{},
	textfmt.APIDiff{},
	textfmt.APIChange{},
}

// fieldTypeOverrides allows specific struct fields to use a hand-crafted TS
// type instead of the reflect-derived one. Key format: "TypeName.json_field_name".
// Use sparingly — only for well-known string enumerations where Go uses plain
// string but the frontend benefits from a union-literal type.
var fieldTypeOverrides = map[string]string{
	// TypeSupport.status is one of three known values; Go uses plain string.
	"TypeSupport.status": `"typed" | "stubs" | "untyped"`,
	// DocSymbol.kind is one of three known values; Go uses plain string.
	"DocSymbol.kind": `"function" | "class" | "exception"`,
}

func main() {
	out := flag.String("out", "", "TypeScript output file path (required)")
	openapiOut := flag.String("openapi", "", "OpenAPI 3.1 JSON output file path (optional)")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "gentypes: -out flag is required")
		os.Exit(1)
	}

	buf, err := generate(contract)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gentypes: %v\n", err)
		os.Exit(1)
	}
	writeOut(*out, buf)

	if *openapiOut != "" {
		doc, err := buildOpenAPI(contract, routes)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gentypes: openapi: %v\n", err)
			os.Exit(1)
		}
		spec, err := marshalOpenAPI(doc)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gentypes: openapi: %v\n", err)
			os.Exit(1)
		}
		writeOut(*openapiOut, spec)
	}
}

// writeOut writes buf to path, exiting non-zero on failure.
func writeOut(path string, buf []byte) {
	if err := os.WriteFile(path, buf, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gentypes: write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gentypes: wrote %s (%d bytes)\n", path, len(buf))
}

// generate produces the TypeScript source for the given contract types.
func generate(types []any) ([]byte, error) {
	// Build a set of registered type names for inline-struct detection.
	registered := make(map[string]bool, len(types))
	for _, v := range types {
		t := reflect.TypeOf(v)
		registered[t.Name()] = true
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by api/cmd/gentypes. DO NOT EDIT.\n")
	buf.WriteString("// Re-generate with: cd api && go run ./cmd/gentypes -out ../web/app/types/api.gen.ts\n\n")

	for i, v := range types {
		t := reflect.TypeOf(v)
		if t.Kind() != reflect.Struct {
			return nil, fmt.Errorf("contract entry %T is not a struct", v)
		}
		emitInterface(&buf, t, registered)
		// Separate interfaces with a blank line; file ends with the closing brace + newline.
		if i < len(types)-1 {
			buf.WriteByte('\n')
		}
	}

	return buf.Bytes(), nil
}

// emitInterface writes a single TypeScript interface declaration.
func emitInterface(buf *bytes.Buffer, t reflect.Type, registered map[string]bool) {
	fmt.Fprintf(buf, "export interface %s {\n", t.Name())
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		tag, omit, skip := parseJSONTag(f)
		if skip {
			continue
		}
		// Check for a hand-crafted type override keyed by "TypeName.json_field".
		overrideKey := t.Name() + "." + tag
		var tsType string
		if override, ok := fieldTypeOverrides[overrideKey]; ok {
			tsType = override
		} else {
			tsType = goTypeToTS(f.Type, registered)
		}
		optional := ""
		if omit {
			optional = "?"
		}
		fmt.Fprintf(buf, "  %s%s: %s;\n", tag, optional, tsType)
	}
	buf.WriteString("}\n")
}

// parseJSONTag returns (jsonName, omitempty, skip).
// skip=true when the field has json:"-" or is unexported.
func parseJSONTag(f reflect.StructField) (name string, omitempty bool, skip bool) {
	if !f.IsExported() {
		return "", false, true
	}
	raw := f.Tag.Get("json")
	if raw == "-" {
		return "", false, true
	}
	parts := strings.Split(raw, ",")
	name = parts[0]
	if name == "" {
		name = f.Name
	}
	for _, p := range parts[1:] {
		if p == "omitempty" {
			omitempty = true
		}
	}
	return name, omitempty, false
}

// goTypeToTS converts a Go reflect.Type into the corresponding TypeScript type string.
func goTypeToTS(t reflect.Type, registered map[string]bool) string {
	// Unwrap pointer: *T → T | null
	if t.Kind() == reflect.Pointer {
		inner := goTypeToTS(t.Elem(), registered)
		return inner + " | null"
	}

	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice:
		elem := goTypeToTS(t.Elem(), registered)
		return elem + "[]"
	case reflect.Map:
		valType := goTypeToTS(t.Elem(), registered)
		return "Record<string, " + valType + ">"
	case reflect.Struct:
		name := t.Name()
		// time.Time → string
		if t.PkgPath() == "time" && name == "Time" {
			return "string"
		}
		// Registered type → reference by name
		if registered[name] {
			return name
		}
		// Anonymous/unregistered struct — inline as object type
		return inlineStruct(t, registered)
	}
	return "unknown"
}

// inlineStruct renders an unregistered struct as an inline TS object literal type.
func inlineStruct(t reflect.Type, registered map[string]bool) string {
	var parts []string
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		tag, omit, skip := parseJSONTag(f)
		if skip {
			continue
		}
		opt := ""
		if omit {
			opt = "?"
		}
		tsType := goTypeToTS(f.Type, registered)
		parts = append(parts, fmt.Sprintf("%s%s: %s", tag, opt, tsType))
	}
	return "{ " + strings.Join(parts, "; ") + " }"
}
