// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[ILLEGAL-1]
	_ = x[NEWLINE-2]
	_ = x[INDENT-3]
	_ = x[DEDENT-4]
	_ = x[NAME-5]
	_ = x[NUMBER-6]
	_ = x[STRING-7]
	_ = x[DEF-8]
	_ = x[CLASS-9]
	_ = x[IMPORT-10]
	_ = x[FROM-11]
	_ = x[AS-12]
	_ = x[IF-13]
	_ = x[ELIF-14]
	_ = x[ELSE-15]
	_ = x[ASYNC-16]
	_ = x[RETURN-17]
	_ = x[RAISE-18]
	_ = x[PASS-19]
	_ = x[NONE-20]
	_ = x[TRUE-21]
	_ = x[FALSE-22]
	_ = x[TYPE-23]
	_ = x[FOR-24]
	_ = x[WHILE-25]
	_ = x[TRY-26]
	_ = x[EXCEPT-27]
	_ = x[FINALLY-28]
	_ = x[WITH-29]
	_ = x[MATCH-30]
	_ = x[CASE-31]
	_ = x[YIELD-32]
	_ = x[DEL-33]
	_ = x[GLOBAL-34]
	_ = x[NONLOCAL-35]
	_ = x[ASSERT-36]
	_ = x[LAMBDA-37]
	_ = x[AND-38]
	_ = x[OR-39]
	_ = x[NOT-40]
	_ = x[IN-41]
	_ = x[IS-42]
	_ = x[ARROW-43]
	_ = x[COLON-44]
	_ = x[ASSIGN-45]
	_ = x[PIPE-46]
	_ = x[STAR-47]
	_ = x[DSTAR-48]
	_ = x[DOT-49]
	_ = x[ELLIPSIS-50]
	_ = x[SLASH-51]
	_ = x[AT-52]
	_ = x[COMMA-53]
	_ = x[SEMI-54]
	_ = x[PLUS-55]
	_ = x[MINUS-56]
	_ = x[WALRUS-57]
	_ = x[EQ-58]
	_ = x[NEQ-59]
	_ = x[LT-60]
	_ = x[GT-61]
	_ = x[LTE-62]
	_ = x[GTE-63]
	_ = x[TILDE-64]
	_ = x[AMPER-65]
	_ = x[CARET-66]
	_ = x[PERCENT-67]
	_ = x[LSHIFT-68]
	_ = x[RSHIFT-69]
	_ = x[DSLASH-70]
	_ = x[LPAREN-71]
	_ = x[RPAREN-72]
	_ = x[LBRACK-73]
	_ = x[RBRACK-74]
	_ = x[LBRACE-75]
	_ = x[RBRACE-76]
}

const _Type_name = "EOFILLEGALNEWLINEINDENTDEDENTNAMENUMBERSTRINGDEFCLASSIMPORTFROMASIFELIFELSEASYNCRETURNRAISEPASSNONETRUEFALSETYPEFORWHILETRYEXCEPTFINALLYWITHMATCHCASEYIELDDELGLOBALNONLOCALASSERTLAMBDAANDORNOTINISARROWCOLONASSIGNPIPESTARDSTARDOTELLIPSISSLASHATCOMMASEMIPLUSMINUSWALRUSEQNEQLTGTLTEGTETILDEAMPERCARETPERCENTLSHIFTRSHIFTDSLASHLPARENRPARENLBRACKRBRACKLBRACERBRACE"

var _Type_index = [...]uint16{0, 3, 10, 17, 23, 29, 33, 39, 45, 48, 53, 59, 63, 65, 67, 71, 75, 80, 86, 91, 95, 99, 103, 108, 112, 115, 120, 123, 129, 136, 140, 145, 149, 154, 157, 163, 171, 177, 183, 186, 188, 191, 193, 195, 200, 205, 211, 215, 219, 224, 227, 235, 240, 242, 247, 251, 255, 260, 266, 268, 271, 273, 275, 278, 281, 286, 291, 296, 303, 309, 315, 321, 327, 333, 339, 345, 351, 357}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
